#!/bin/bash
#SBATCH --job-name=kbo_test      # Job name
#SBATCH --partition=murray-clay             # queue for job submission
#SBATCH --account=murray-clay               # queue for job submission
#SBATCH --mail-type=ALL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=arhermos@ucsc.edu   # Where to send mail
#SBATCH --ntasks=1                  # Number of MPI ranks
#SBATCH --nodes=1                    # Number of nodes
#SBATCH --ntasks-per-node=1         # How many tasks on each node
#SBATCH --time=12:00:00              # Time limit hrs:min:sec
#SBATCH --output=kbo_test_%j.log     # Standard output and error log


pwd; hostname; date

module load python/3.6.7 
module load numpy/1.17.0 
module load matplotlib/3.1.1
module load pandas/0.25.1

python -u migrate.py

date 
